# Generated by Django 4.0.2 on 2022-06-01 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_info',
            name='percentage',
            field=models.IntegerField(choices=[(1, '60%'), (2, '100%')], default=0),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='session',
            field=models.IntegerField(choices=[(1, 91.77272727272727), (2, 96.19047619047619), (3, 91.86363636363636)], default=0),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentfees', to=settings.AUTH_USER_MODEL),
        ),
    ]
