# Generated by Django 4.0.2 on 2022-06-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_payment_info_percentage_payment_info_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='percentage',
            field=models.IntegerField(choices=[(1, '60%'), (2, '100%')], default=1),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='session',
            field=models.IntegerField(choices=[(1, '2019/20'), (2, '2020/21'), (3, '2021/22')], default=1),
        ),
    ]
